words = {
    'zdobyć umiejętność': 'learn a skill',
    'marzyć o': 'dream of',
    'przedstawiać sztuczki': 'demonstrate tricks',
    'przemieszczać się': 'move around',
    'wygrać nagrodę': 'win a prize',
    'rozpoznawać gwiazdy': 'identify stars',
    'spotykać naukowców': 'meet scientists',
    'szkoła letnia': 'summer school',
    'lot w tunelu aerodynamicznym': 'indoor skydiving',
    'zajęcia praktyczne': 'practical activities',
    'stęskniony za domem (krajem)': 'homesick',
    'gospodarz': 'host',
    'luksusowy': 'luxury',
    'rozgościć się, czuć się jak u siebie': 'feel at home',
    'łódź mieszkalna; barka mieszkalna': 'houseboat',
    'społeczność; wspólnota': 'community',
    'kanapa': 'couch',
    'za darmo, darmowy': 'free',
    'zakwaterowanie': 'accommodation',
    'wilgotny': 'humid',
    'las deszczowy': 'rainforest',
    'domek na drzewie': 'treehouse',
    'wulkaniczny': 'volcanic',
    'przeprowadzić się': 'move house',
    'gorące źródło': 'hot spring',
    'zatłoczony': 'busy',
    'upalny/upalnie': 'scorching',
    'centrum handlu': 'trading centre',
    'korek uliczny': 'traffic jam',
    'skała': 'rock',
    'bujny; luksusowy, bogaty': 'lush',
    'pomnik': 'monument',
    'roślinność': 'vegetation',
    'turkus': 'turquoise',
    'opuszczać; zaniechać; rezygnować': 'abandon',
    'koczowniczy; wędrowny': 'nomadic',
    'kołek, pal, szczudło': 'stilt',
    'górniczy': 'mining',
    'góra': 'mountain',
    'wulkan': 'volcano',
    'przyciągać; zachwycać': 'attract',
    'plemię; szczep': 'tribe',
    'wielbłąd': 'camel',
    'krater; lej': 'crater'
}
