words = {
    'zdobyć umiejętność': 'learn a skill',
    'marzyć o': 'dream of',
    'przedstawiać sztuczki': 'demonstrate tricks',
    'przemieszczać się': 'move around',
    'wygrać nagrodę': 'win a prize',
    'rozpoznawać gwiazdy': 'identify stars',
    'spotykać naukowców': 'meet scientists',
    'szkoła letnia': 'summer school',
    'lot w tunelu aerodynamicznym': 'indoor skydiving',
    'zajęcia praktyczne': 'practical activities',
    'stęskniony za domem (krajem)': 'homesick',
    'gospodarz': 'host',
    'luksusowy': 'luxury',
    'rozgościć się, czuć się jak u siebie': 'feel at home',
    'łódź mieszkalna; barka mieszkalna': 'houseboat',
    'społeczność; wspólnota': 'community',
    'kanapa': 'couch',
    'za darmo, darmowy': 'free',
    'zakwaterowanie': 'accommodation',
    'wilgotny': 'humid',
    'las deszczowy': 'rainforest',
    'domek na drzewie': 'treehouse',
    'wulkaniczny': 'volcanic',
    'przeprowadzić się': 'move house',
    'gorące źródło': 'hot spring',
    'zatłoczony': 'busy',
    'upalny/upalnie': 'scorching',
    'centrum handlu': 'trading centre',
    'korek uliczny': 'traffic jam',
    'skała': 'rock',
    'bujny; luksusowy, bogaty': 'lush',
    'pomnik': 'monument',
    'roślinność': 'vegetation',
    'turkus': 'turquoise',
    'opuszczać; zaniechać; rezygnować': 'abandon',
    'koczowniczy; wędrowny': 'nomadic',
    'kołek, pal, szczudło': 'stilt',
    'górniczy': 'mining',
    'góra': 'mountain',
    'wulkan': 'volcano',
    'przyciągać; zachwycać': 'attract',
    'plemię; szczep': 'tribe',
    'wielbłąd': 'camel',
    'krater; lej': 'crater',
    'krajobraz; pejzaż': 'landscape',
    'wykształcić umiejętność widzenia pod wodą': 'develop underwater vision',
    'elektryczność': 'electricity',
    'jaskinia; pieczara': 'cave',
    'gęsty; spoisty; tępawy': 'dense',
    'zapierający dech': 'breathtaking',
    'cel wycieczek turystycznych': 'tourist destination',
    'robiący wrażenie; imponujący': 'impressive',
    'suchy': 'dry',
    'zaludnienie; ludność, populacja': 'population',
    'pustynia': 'desert',
    'dawny; stary; starożytny': 'ancient',
    'wyspa': 'island',
    'ruina; gruzy': 'ruin',
    'lampa': 'lamp',
    'nie wpuszczać kogoś': 'keep somebody out',
    'wpuścić kogoś do środka': 'let somebody in',
    'pamiątka': 'souvenir',
    'zostawać w domu; siedzieć w domu': 'stay in',
    'wydostać się z': 'get away from',
    'muszla; łupina; skorupa': 'shell',
    'przychodzić; odwiedzać': 'come around',
    'naprawdę': 'really',
    'na szczęście': 'luckily',
    'nieco; trochę': 'slightly',
    'zupełnie; kompletnie; całkowicie': 'completely',
    'całkiem zdrowy': 'rather healthy',
    'dość szybko': 'pretty fast',
    'nie kłaść się spać': 'stay up',
    'źle': 'badly',
    'trochę': 'a little',
    'dobrze': 'well',
    'niewiarygodnie': 'unbelievably',
    'niezwykle; niezmiernie': 'extremely',
    'dość blisko': 'quite near',
    'rozrywka; rozbawienie': 'entertainment',
    'polecać': 'recommend',
    'recommend': 'speciality',
    'specjalność': 'speciality',
    'pieszo': 'on foot',
    'słynący z': 'famous for',
    'nocne życie': 'nightlife',
    'konieczność': 'a must',
    'według, zgodnie z': 'according to',
    'cudowny; wspaniały': 'wonderful',
    'zabytek, historyczne miejsce': 'historic site',
    'mieć tendencję (do czegoś)': 'tend to',
    'kurtka zimowa': 'winter coat',
    'wybór; dobór; selekcja': 'selection',
    'pyszny; wyborny': 'delicious',
    'śliczny; miły; słodki': 'lovely',
    'główna atrakcja turystyczna': 'tourist highlight',
    'architektura': 'architecture',
    'atrakcja; przyciąganie': 'attraction',
    'zamek': 'castle',
    'restauracja nad wodą': 'waterfront restaurant',
    'rodzina królewska': 'royal family',
    'wzgórze; pagórek': 'hill',
    'rzeka': 'river',
    'dorosły': 'adult',
    'odpowiedni; stosowny': 'suitable',
    'dzienny; codzienny': 'daily',
    'sufit': 'ceiling',
    'ostrzegać; przestrzegać; uprzedzać': 'warn',
    'parapetówka': 'house-warming party',
    'prześcieradło': 'sheet',
    'przebrać się za kogoś': 'dress up as'
}
